### ISSUE TITLE
How to implement for `Predator PH315-52` model?

### ISSUE THREAD

**Issue by mmsaeed509** [snowyoneill/Linux-PredatorSense#1]
Hi, how did you change the [clone](https://github.com/mohsunb/PredatorSense) for your model?
as I want to change your clone for  `Predator PH315-52` model

also, I'm going to plan to build a new ISO release of  [**`Exodia OS`**](https://exodia-os.github.io/exodia-website/) Predator edition 

that will auto-detect the Laptop model and install the proper Predator Sense GUI

**Comment by snowyoneill** [comment]
@mmsaeed509 you'll need to use an EC reader program like [RW Everything](http://rweverything.com/) ( in Windows ) to monitor the register values and map these to the readouts in PredatorSense software.

From what i can gather this should work for similar models, however its not guaranteed. Acer may have changed register mappings between different laptop versions.

**Comment by mmsaeed509** [comment]
OK, I'll try to monitor the register values and map 
Thanks!

**Comment by snowyoneill** [comment]
Coolios

**Comment by snowyoneill** [comment]
@mmsaeed509 Just an FYI the current app *should* work with your laptop without modification. So far from the laptops its been tested on it looks like the EC codes are the same.
