### ISSUE TITLE
The module ec_sys is not present in kernels higher than 5.11.2

### ISSUE THREAD

**Issue by lestcape** [snowyoneill/Linux-PredatorSense#3]
Please see:
https://bugzilla.redhat.com/show_bug.cgi?id=1943318

Or this proposed workaround, that use a kernel module to recover the functionality:
https://github.com/YoyPa/isw/issues/265#issue-1419231642

**Comment by lestcape** [comment]
> @lestcape I have already read through those resources as I ran into that error when i tried to update Ubuntu to 22.04. Using the above commands worked to restore access to the EC. As for the other distros i cannot comment as i have not tested them.

If Ubuntu re-added the module somehow (probably just they compiled the kernel with an option to enable the module), i don' t know. In Debian 12 with the Linux kernel 6.1:

![Captura desde 2023-07-11 10-56-28](https://github.com/snowyoneill/Linux-PredatorSense/assets/43790722/1f4ba365-013d-4b4b-bde7-88944045b868)

**Comment by snowyoneill** [comment]
@lestcape yeah this code was only tested against Ubuntu 20.04 with an earlier kernel before they removed the access to the EC. If you follow the steps you posted and install [acpi_ec](https://github.com/MusiKid/acpi_ec) then you can update the `EC_IO_FILE` variable in [ecwrite.py](https://github.com/snowyoneill/Linux-PredatorSense/blob/77c96e5b9f5ee8076909ed9c4c447656d99fd86c/ecwrite.py#L1) to point to the new path and then the program should work.

And im 100% behind on the idea of releasing the program as a deb or package of some sort. I have not had a chance to look into that but willing to work on it with you.

**Comment by lestcape** [comment]
Yes, this should be the idea, but it need to be tested and if is working then modify the app to allow both uri. If one fail then we should use the another and if both fails, the app should show a message and do not crash, but currently the app crash.

By the way, seem to be that [acpi_ec](https://github.com/MusiKid/acpi_ec) is compatible with secure boot, but [msr-tools](https://github.com/intel/msr-tools) is not compatible. Should be good to also have compatibility with secure boot from both and apparently this is probably possible if we fork the [msr-tools](https://github.com/intel/msr-tools) and modify it. See: https://github.com/intel/intel-cmt-cat/wiki/UEFI-Secure-Boot-Compatibility. Also should be good to have support for the turbo button. My turbo button works with the Jafar kernel module: https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module. Is the only thing that aparently really work with this module and my laptop.

Unfortunately i have not time for now to do all that things. But i promised that was going to test your fork and well, I'm just reporting what I could see. There are more problems really, but they are related to Qt and I really don't know much about pyQt.

**Comment by snowyoneill** [comment]
@lestcape closing this issue. I have updated the code to point to the `acpi_ec` path if it exists. I've also updated the README to reflect that `msr-tools` and `undervolt` are now optional. Without installing these packages the app should still work, you will simply no longer see the voltage read outs, historical chart or be able to make changes to the CPU offsets.
