### ISSUE TITLE
Error read EC register for Charge Limit: 1

### ISSUE THREAD

**Issue by alexsoluweb** [snowyoneill/Linux-PredatorSense#8]
Hi, i did install everyhting and i got this error while running the app:

Error read EC register for Charge Limit: 1

```
$ sudo dmidecode -t system
# dmidecode 3.5
Getting SMBIOS data from sysfs.
SMBIOS 3.3.0 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: Acer
	Product Name: Predator PH315-54
	Version: V1.15
	Serial Number: ****
	UUID: ****
	Wake-up Type: Power Switch
	SKU Number: *****
	Family: Predator Helios 300

$ uname -r
6.8.0-45-generic

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

**Comment by alexsoluweb** [comment]
Omg it works now... You are a genius!

**Comment by alexsoluweb** [comment]
Omg it works now... You are a genius thank you so much man!

**Comment by snowyoneill** [comment]
Haha thanks buddy! I just saw your comment over in `nbfc-linux`. How did you end up fixing the read error for the charge limit?

**Comment by alexsoluweb** [comment]
I'm not sure what make it clear the error... i did `chmod 600 /dev/ec`  also randomly checked misc options in the app, then a reboot and it worked out. I dunno what are those options in misc. Are they documented somewhere? Anyway thank you again man you make my day, i have been trying to fix this for days and this was starting to drive me crazy man... lol

**Comment by snowyoneill** [comment]
Ok good to know. So you had to add full read and write to the `/dev/ec` - can you type  `history` on the terminal and see if you have any other relevant commands to enable the app. I can then add them to the README.

On the documentation of the Misc features, these are taken directly from Windows. In descending order they are `KB Timeout` ( toggle 30 sec keyboard timeout ), `LCD Overdrive` ( toggle faster response times on supported panels ), `USB Charging` ( toggle charging USB devices whilst your laptop lid is closed ) and lastly `Charge Limit` ( limit battery charging to 80% - to perverse long term health )

**Comment by alexsoluweb** [comment]
Ok good to know! Yah on history it's pretty much what i did.  Nothing else relevant. Again thank you so much for this nice work!

**Comment by snowyoneill** [comment]
Solid solid. Absolutely, thanks for checking!
